---
- name: Set and Lock Wallpaper for All Users (Linux Mint Cinnamon)
  hosts: Madurai-OP
  become: yes
  gather_facts: false

  tasks:

    - name: Ensure /usr/share/mywallpapers directory exists
      file:
        path: /usr/share/mywallpapers
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy wallpaper to /usr/share/mywallpapers/Test.jpg
      copy:
        src: "Desktop_Wallpaper_Week_15.jpg"   # must be in playbook dir or files/
        dest: "/usr/share/mywallpapers/Test.jpg"
        owner: root
        group: root
        mode: '0644'

    - name: Set permissions so only root can change wallpaper file
      file:
        path: /usr/share/mywallpapers/Test.jpg
        owner: root
        group: root
        mode: '0644'

    - name: Create dconf config directory
      file:
        path: "/etc/dconf/db/local.d"
        state: directory
        mode: '0755'

    - name: Create dconf lock directory
      file:
        path: "/etc/dconf/db/local.d/locks"
        state: directory
        mode: '0755'

    - name: Ensure /etc/dconf/profile directory exists
      file:
        path: "/etc/dconf/profile"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Set system-wide default wallpaper for Cinnamon
      copy:
        dest: "/etc/dconf/db/local.d/00-wallpaper"
        content: |
          [org/cinnamon/desktop/background]
          picture-uri='file:///usr/share/mywallpapers/Test.jpg'
          picture-options='zoom'

    - name: Lock wallpaper settings so users cannot change them (Cinnamon)
      copy:
        dest: "/etc/dconf/db/local.d/locks/desktop-background"
        content: |
          /org/cinnamon/desktop/background/picture-uri
          /org/cinnamon/desktop/background/picture-options

    - name: Ensure dconf profile exists
      copy:
        dest: /etc/dconf/profile/user
        content: |
          user-db:user
          system-db:local

    - name: Update dconf database
      command: dconf update

    - name: Force wallpaper for active user sessions
      shell: |
        for user in $(who | awk '{print $1}' | sort -u); do
          uid=$(id -u $user)
          export DISPLAY=:0
          sudo -u "$user" \
          DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" \
          gsettings set org.cinnamon.desktop.background picture-uri 'file:///usr/share/mywallpapers/Test.jpg'
          sudo -u "$user" \
          DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" \
          gsettings set org.cinnamon.desktop.background picture-options 'zoom'
        done
      ignore_errors: yes
